-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activity_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  activity_id uuid NOT NULL,
  log_date date NOT NULL,
  status USER-DEFINED NOT NULL,
  value jsonb DEFAULT '{}'::jsonb,
  notes text,
  logged_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT activity_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT activity_logs_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.discipline_activities(id)
);
CREATE TABLE public.alarms (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  interval_hours integer DEFAULT 0 CHECK (interval_hours >= 0 AND interval_hours <= 23),
  interval_minutes integer DEFAULT 0 CHECK (interval_minutes >= 0 AND interval_minutes <= 59),
  is_test_mode boolean DEFAULT false,
  test_interval_minutes integer DEFAULT 5 CHECK (test_interval_minutes >= 1 AND test_interval_minutes <= 5),
  day_start_time time without time zone NOT NULL DEFAULT '08:00:00'::time without time zone,
  day_end_time time without time zone NOT NULL DEFAULT '22:00:00'::time without time zone,
  active_days ARRAY NOT NULL DEFAULT '{t,t,t,t,t,t,t}'::boolean[] CHECK (array_length(active_days, 1) = 7),
  is_enabled boolean DEFAULT true,
  last_triggered_at timestamp with time zone,
  next_trigger_at timestamp with time zone,
  sound_type text DEFAULT 'default'::text,
  local_id text,
  migrated_from_local boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  synced_at timestamp with time zone,
  deleted_at timestamp with time zone,
  CONSTRAINT alarms_pkey PRIMARY KEY (id),
  CONSTRAINT alarms_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  name text NOT NULL,
  color text DEFAULT '#6366f1'::text,
  icon text,
  is_system boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  description text,
  order_index integer DEFAULT 0,
  is_archived boolean DEFAULT false,
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT categories_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.challenge_activities (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  challenge_id uuid NOT NULL,
  activity_id uuid NOT NULL,
  is_required boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT challenge_activities_pkey PRIMARY KEY (id),
  CONSTRAINT challenge_activities_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.discipline_activities(id),
  CONSTRAINT challenge_activities_challenge_id_fkey FOREIGN KEY (challenge_id) REFERENCES public.challenges(id)
);
CREATE TABLE public.challenge_activity_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  challenge_id uuid NOT NULL,
  activity_log_id uuid NOT NULL,
  approval_status USER-DEFINED DEFAULT 'pending'::challenge_log_approval_status,
  approved_by uuid,
  approved_at timestamp with time zone,
  rejection_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT challenge_activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT challenge_activity_logs_challenge_id_fkey FOREIGN KEY (challenge_id) REFERENCES public.challenges(id),
  CONSTRAINT challenge_activity_logs_activity_log_id_fkey FOREIGN KEY (activity_log_id) REFERENCES public.activity_logs(id),
  CONSTRAINT challenge_activity_logs_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.challenge_participants (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  challenge_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['creator'::text, 'participant'::text, 'accountability_partner'::text])),
  status USER-DEFINED DEFAULT 'invited'::challenge_participant_status,
  joined_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT challenge_participants_pkey PRIMARY KEY (id),
  CONSTRAINT challenge_participants_challenge_id_fkey FOREIGN KEY (challenge_id) REFERENCES public.challenges(id),
  CONSTRAINT challenge_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.challenges (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  creator_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  start_date date NOT NULL,
  end_date date NOT NULL,
  status USER-DEFINED DEFAULT 'draft'::challenge_status,
  prize_amount numeric DEFAULT 0.00,
  prize_currency text DEFAULT 'USD'::text,
  is_public boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  urgency_level text CHECK (urgency_level = ANY (ARRAY['critical'::text, 'high'::text, 'medium'::text])),
  failure_consequence text CHECK (failure_consequence = ANY (ARRAY['charity'::text, 'partner'::text, 'platform'::text, 'anti-charity'::text])),
  payment_intent_id text,
  payment_status text CHECK (payment_status = ANY (ARRAY['pending'::text, 'paid'::text, 'failed'::text, 'canceled'::text, 'refunded'::text])),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  failed_at timestamp with time zone,
  CONSTRAINT challenges_pkey PRIMARY KEY (id),
  CONSTRAINT challenges_user_id_fkey FOREIGN KEY (creator_id) REFERENCES auth.users(id)
);
CREATE TABLE public.competition_participants (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  competition_id uuid NOT NULL,
  user_id uuid NOT NULL,
  current_score numeric DEFAULT 0,
  rank integer,
  last_updated_at timestamp with time zone DEFAULT now(),
  joined_at timestamp with time zone DEFAULT now(),
  CONSTRAINT competition_participants_pkey PRIMARY KEY (id),
  CONSTRAINT competition_participants_competition_id_fkey FOREIGN KEY (competition_id) REFERENCES public.discipline_competitions(id),
  CONSTRAINT competition_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.daily_reminders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  is_enabled boolean DEFAULT true,
  reminder_time time without time zone NOT NULL DEFAULT '20:00:00'::time without time zone,
  reminder_channels jsonb DEFAULT '{"sms": false, "push": true, "alarm": false, "email": false}'::jsonb,
  reminder_days ARRAY DEFAULT ARRAY[0, 1, 2, 3, 4, 5, 6],
  custom_message text DEFAULT 'Time to track your daily activities!'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT daily_reminders_pkey PRIMARY KEY (id),
  CONSTRAINT daily_reminders_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.discipline_activities (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  goal_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  tracking_type USER-DEFINED NOT NULL DEFAULT 'boolean'::tracking_type,
  target_config jsonb NOT NULL DEFAULT '{}'::jsonb,
  frequency_type USER-DEFINED DEFAULT 'daily'::frequency_type,
  frequency_config jsonb DEFAULT '{}'::jsonb,
  reminder_enabled boolean DEFAULT false,
  reminder_time time without time zone,
  reminder_channels jsonb DEFAULT '{"sms": false, "push": true, "alarm": false, "email": false}'::jsonb,
  current_streak integer DEFAULT 0,
  longest_streak integer DEFAULT 0,
  streak_freeze_available boolean DEFAULT true,
  last_freeze_used_at date,
  is_active boolean DEFAULT true,
  order_index integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT discipline_activities_pkey PRIMARY KEY (id),
  CONSTRAINT discipline_activities_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT discipline_activities_goal_id_fkey FOREIGN KEY (goal_id) REFERENCES public.goals(id)
);
CREATE TABLE public.discipline_competitions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_by uuid NOT NULL,
  name text NOT NULL,
  description text,
  competition_type text DEFAULT 'completion_rate'::text CHECK (competition_type = ANY (ARRAY['completion_rate'::text, 'streak'::text, 'total_activities'::text, 'category_specific'::text])),
  category_id uuid,
  start_date date NOT NULL,
  end_date date NOT NULL,
  is_active boolean DEFAULT true,
  is_public boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT discipline_competitions_pkey PRIMARY KEY (id),
  CONSTRAINT discipline_competitions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT discipline_competitions_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.discipline_friends (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  friend_id uuid NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'blocked'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT discipline_friends_pkey PRIMARY KEY (id),
  CONSTRAINT discipline_friends_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT discipline_friends_friend_id_fkey FOREIGN KEY (friend_id) REFERENCES auth.users(id)
);
CREATE TABLE public.goals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  category_id uuid,
  title text NOT NULL,
  description text,
  specific text,
  measurable text,
  achievable text,
  relevant text,
  time_bound text,
  target_date date,
  status USER-DEFINED DEFAULT 'active'::goal_status,
  progress_percentage integer DEFAULT 0 CHECK (progress_percentage >= 0 AND progress_percentage <= 100),
  manual_progress_override integer,
  use_manual_progress boolean DEFAULT false,
  order_index integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT goals_pkey PRIMARY KEY (id),
  CONSTRAINT goals_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT goals_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id)
);
CREATE TABLE public.manifestation_entries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  description text NOT NULL DEFAULT ''::text,
  category text NOT NULL DEFAULT 'Personal'::text,
  target_date date,
  is_completed boolean DEFAULT false,
  completed_at timestamp with time zone,
  visualization_notes text,
  affirmations ARRAY DEFAULT '{}'::text[],
  local_id text,
  migrated_from_local boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  synced_at timestamp with time zone,
  deleted_at timestamp with time zone,
  CONSTRAINT manifestation_entries_pkey PRIMARY KEY (id),
  CONSTRAINT manifestation_entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.manifestation_read_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  manifestation_id uuid NOT NULL,
  user_id uuid NOT NULL,
  read_at timestamp with time zone NOT NULL DEFAULT now(),
  mood_entry_id uuid,
  read_duration_seconds integer CHECK (read_duration_seconds IS NULL OR read_duration_seconds >= 0),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT manifestation_read_history_pkey PRIMARY KEY (id),
  CONSTRAINT manifestation_read_history_mood_entry_id_fkey FOREIGN KEY (mood_entry_id) REFERENCES public.mood_entries(id),
  CONSTRAINT manifestation_read_history_manifestation_id_fkey FOREIGN KEY (manifestation_id) REFERENCES public.manifestation_entries(id),
  CONSTRAINT manifestation_read_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.mood_entries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  mood integer NOT NULL CHECK (mood >= 1 AND mood <= 5),
  notes text DEFAULT ''::text,
  tags ARRAY DEFAULT '{}'::text[],
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  alarm_id uuid,
  alarm_name text,
  manifestation_read boolean DEFAULT false,
  local_id text,
  migrated_from_local boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  synced_at timestamp with time zone,
  deleted_at timestamp with time zone,
  CONSTRAINT mood_entries_pkey PRIMARY KEY (id),
  CONSTRAINT mood_entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT mood_entries_alarm_id_fkey FOREIGN KEY (alarm_id) REFERENCES public.alarms(id)
);
CREATE TABLE public.payment_transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  challenge_id uuid NOT NULL,
  payment_intent_id text NOT NULL,
  amount integer NOT NULL,
  platform_fee integer,
  currency text NOT NULL DEFAULT 'USD'::text,
  status text NOT NULL CHECK (status = ANY (ARRAY['pending'::text, 'paid'::text, 'refunded'::text, 'transferred'::text])),
  transfer_id text,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT payment_transactions_challenge_id_fkey FOREIGN KEY (challenge_id) REFERENCES public.challenges(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  display_name text,
  email text UNIQUE,
  avatar_url text,
  timezone text DEFAULT 'UTC'::text,
  notifications_enabled boolean DEFAULT true,
  sound_enabled boolean DEFAULT true,
  theme text DEFAULT 'light'::text CHECK (theme = ANY (ARRAY['light'::text, 'dark'::text])),
  reminder_frequency text CHECK (reminder_frequency = ANY (ARRAY['daily'::text, 'weekly'::text, 'custom'::text])),
  reminder_time time without time zone,
  subscription_status text DEFAULT 'trial'::text CHECK (subscription_status = ANY (ARRAY['trial'::text, 'trial_expired'::text, 'active_monthly'::text, 'active_lifetime'::text, 'active_coupon'::text, 'expired'::text])),
  subscription_expiry timestamp with time zone,
  trial_start_date timestamp with time zone,
  trial_end_date timestamp with time zone,
  coupon_code text,
  coupon_activation_date timestamp with time zone,
  coupon_expiry_date timestamp with time zone,
  has_lifetime_access boolean DEFAULT false,
  local_data_migrated boolean DEFAULT false,
  local_migration_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_seen_at timestamp with time zone,
  subscription_tier text DEFAULT 'free'::text CHECK (subscription_tier = ANY (ARRAY['free'::text, 'pro'::text])),
  subscription_expires_at timestamp with time zone,
  is_admin boolean DEFAULT false,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.shared_progress (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  shared_with text DEFAULT 'friends'::text CHECK (shared_with = ANY (ARRAY['public'::text, 'friends'::text, 'private'::text])),
  share_categories boolean DEFAULT true,
  share_goals boolean DEFAULT true,
  share_completion_rate boolean DEFAULT true,
  share_streaks boolean DEFAULT true,
  share_activity_names boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT shared_progress_pkey PRIMARY KEY (id),
  CONSTRAINT shared_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.sync_queue (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  table_name text NOT NULL,
  record_id uuid NOT NULL,
  operation text NOT NULL CHECK (operation = ANY (ARRAY['INSERT'::text, 'UPDATE'::text, 'DELETE'::text])),
  payload jsonb,
  local_timestamp timestamp with time zone NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  retry_count integer DEFAULT 0,
  last_error text,
  processed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sync_queue_pkey PRIMARY KEY (id),
  CONSTRAINT sync_queue_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);